stages:
  ingest:
    cmd: python src/ingestion/fetch_data.py
    deps:
      - src/ingestion/fetch_data.py
    outs:
      - data/raw/egfr_compounds.csv
  curate:
    cmd: python src/processing/curation.py
    deps:
      - src/processing/curation.py
      - data/raw/egfr_compounds.csv
    outs:
      - data/processed/egfr_curated.csv
  eda:
    cmd: python src/processing/eda.py
    deps:
      - src/processing/eda.py
      - data/processed/egfr_curated.csv
    outs:
      - data/processed/egfr_with_features.csv
      - reports/figures/eda_results.png
  graph_build:
    cmd: python src/processing/graph_construction.py
    deps:
      - src/processing/graph_construction.py
      - data/processed/egfr_with_features.csv
    outs:
      - data/processed/graphs_dataset.pt
  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - src/models/gnn_model.py
      - data/processed/graphs_dataset.pt
    outs:
      - models/gnn_v1.pth